version: '3.4'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tasks-identity
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  identitywebapi:
    image: identitywebapi
    build:
      context: .
      dockerfile: src/services/Identity/Identity.WebAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7124:7124
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - mysql
