version: '3.4'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'tasks-identity'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  identitywebapi:
    depends_on:
      - mysql
    image: identitywebapi
    build:
      context: .
      dockerfile: src/services/Identity/Identity.WebAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    restart: always
